s/find\("lib\/s2s\/fantasy"\)/("@fantasy")/g
s/find\("lib\/s2s\/fantasy\/bestiary"\)/("@bestiary")/g
s/find\("lib\/s2s\/fantasy\/spells"\)/("@spells")/g
s/find\("lib\/s2s\/fantasy\/eras"\)/("@eras")/g
s/find\("lib\/s2s\/fantasy\/worlds"\)/("@worlds-content")/g
s/find\("lib\/s2s\/engine"\)/("@engine")/g
s/find\("lib\/ai"\)/("@engine/utils/ai")/g
s/find\("lib\/ambient"\)/("@engine/ambient")/g
s/find\("lib\/discord"\)/("@engine/utils/discord")/g
s/find\("lib\/grimoire"\)/("@engine/content/grimoire")/g
