// lib/s2s/fantasy/items/armors.ts

import type { Armor } from "./types";

export const FANTASY_ARMORS: Armor[] = [
  {
    key: "leather-armor",
    label: "Armure de Cuir",
    description: "Protection légère, souvent portée par les rôdeurs et voleurs.",
    type: "armor",
    armorType: "light",
    armorClass: 11,
    maxDexBonus: null,
    penaltyStealth: false,
    rarity: "common",
    value: 10,
    weight: 5,
    tags: ["armor", "light"],
  },
  {
    key: "chainmail",
    label: "Cotte de Mailles",
    description: "Mélange solide de protection et de mobilité pour les guerriers.",
    type: "armor",
    armorType: "medium",
    armorClass: 14,
    maxDexBonus: 2,
    penaltyStealth: true,
    rarity: "common",
    value: 75,
    weight: 20,
    tags: ["armor", "medium"],
  },
  {
    key: "plate-armor",
    label: "Armure de Plates",
    description: "Armure lourde offrant une excellente protection mais limitant le mouvement.",
    type: "armor",
    armorType: "heavy",
    armorClass: 18,
    maxDexBonus: 0,
    penaltyStealth: true,
    rarity: "rare",
    value: 1500,
    weight: 30,
    tags: ["armor", "heavy"],
  },
  {
    key: "round-shield",
    label: "Bouclier Rond",
    description: "Bouclier en bois renforcé, améliore la défense générale.",
    type: "armor",
    armorType: "shield",
    armorClass: 2, // bonus de +2 à la CA
    maxDexBonus: null,
    penaltyStealth: false,
    rarity: "common",
    value: 10,
    weight: 3,
    tags: ["armor", "shield"],
  },
  {
    key: "veil-of-mist",
    label: "Voile de Brume",
    description: "Armure légère quasi intangible, idéale pour les mages et éclaireurs.",
    type: "armor",
    armorType: "light",
    armorClass: 13,
    maxDexBonus: null,
    penaltyStealth: false,
    rarity: "very-rare",
    value: 2000,
    weight: 1,
    tags: ["armor", "magic", "stealth"],
  },
];
