// lib/s2s/fantasy/items/weapons.ts

import type { Weapon } from "./types";

export const FANTASY_WEAPONS: Weapon[] = [
  {
    key: "iron-sword",
    label: "Épée de Fer",
    description: "Épée simple mais fiable, très répandue chez les gardes et soldats.",
    type: "weapon",
    handed: "one-handed",
    damage: "1d8",
    damageType: "slashing",
    range: "corps-à-corps",
    properties: ["polyvalente"],
    rarity: "common",
    value: 10,
    weight: 3,
    tags: ["weapon", "melee"],
  },
  {
    key: "oak-staff",
    label: "Bâton de Chêne",
    description: "Bâton solide, utilisé à la fois comme arme et comme symbole de marche.",
    type: "weapon",
    handed: "two-handed",
    damage: "1d6",
    damageType: "bludgeoning",
    range: "corps-à-corps",
    properties: [],
    rarity: "common",
    value: 2,
    weight: 2,
    tags: ["weapon", "melee", "focus"],
  },
  {
    key: "hunter-bow",
    label: "Arc de Chasseur",
    description: "Arc simple utilisé pour la chasse et la guerre légère.",
    type: "weapon",
    handed: "two-handed",
    damage: "1d8",
    damageType: "piercing",
    range: "18m",
    properties: ["munition", "deux-mains"],
    rarity: "common",
    value: 25,
    weight: 1,
    tags: ["weapon", "ranged"],
  },
  {
    key: "shadow-dagger",
    label: "Dague des Ombres",
    description: "Lame fine et sombre, appréciée des voleurs et assassins.",
    type: "weapon",
    handed: "one-handed",
    damage: "1d4",
    damageType: "piercing",
    range: "corps-à-corps / 6m (lancer)",
    properties: ["finesse", "lancer"],
    rarity: "uncommon",
    value: 50,
    weight: 0.5,
    tags: ["weapon", "light", "stealth"],
  },
  {
    key: "ember-greatsword",
    label: "Épée Ardente",
    description: "Grande épée imprégnée d’un feu ancien, dangereuse même au repos.",
    type: "weapon",
    handed: "two-handed",
    damage: "2d6",
    damageType: "slashing",
    range: "corps-à-corps",
    properties: ["lourde"],
    rarity: "rare",
    value: 500,
    weight: 6,
    tags: ["weapon", "magic", "fire"],
  },
];
