import type { GmeMonster } from "../../../modules/gme/types";

export const MONSTERS: GmeMonster[] = [

  // 🐉 CR 17–20 — DRAGONS ANCIENS
  {
    id: "ancient-fire-dragon",
    name: "Dragon de Feu Ancien",
    world: "Fantasy",
    cr: 20,
    category: "dragon",
    biomeTags: ["volcano", "mountain", "underground-lava"],
    habitatTags: ["dragon-lair"],
  },
  {
    id: "ancient-ice-dragon",
    name: "Dragon de Givre Ancien",
    world: "Fantasy",
    cr: 19,
    category: "dragon",
    biomeTags: ["tundra", "glacier"],
    habitatTags: ["dragon-lair"],
  },
  {
    id: "ancient-tempest-dragon",
    name: "Dragon des Tempêtes Ancien",
    world: "Fantasy",
    cr: 20,
    category: "dragon",
    biomeTags: ["storm", "mountain", "sky"],
    habitatTags: ["dragon-lair"],
  },
  {
    id: "ancient-void-dragon",
    name: "Dragon des Ombres Vénérable",
    world: "Fantasy",
    cr: 19,
    category: "dragon",
    biomeTags: ["shadowlands", "void"],
    habitatTags: ["underdark"],
  },
  {
    id: "primordial-stone-dragon",
    name: "Dragon de Pierre Primordial",
    world: "Fantasy",
    cr: 18,
    category: "dragon",
    biomeTags: ["mountain", "cave"],
    habitatTags: ["underground"],
  },
  {
    id: "primordius-dragon",
    name: "Dragon des Profondeurs",
    world: "Fantasy",
    cr: 20,
    category: "dragon",
    biomeTags: ["abyss", "void"],
    habitatTags: ["abyss"],
  },
  {
    id: "solar-dragon",
    name: "Dragon Zénith",
    world: "Fantasy",
    cr: 19,
    category: "dragon",
    biomeTags: ["sun", "sky", "mountain"],
    habitatTags: ["dragon-lair"],
  },
  {
    id: "lunar-dragon",
    name: "Dragon Lunaire",
    world: "Fantasy",
    cr: 19,
    category: "dragon",
    biomeTags: ["moon", "night", "astral"],
    habitatTags: ["astral"],
  },
  {
    id: "crystal-ancient-dragon",
    name: "Dragon Cristallin Ancien",
    world: "Fantasy",
    cr: 17,
    category: "dragon",
    biomeTags: ["crystal-caves", "mountain"],
    habitatTags: ["underground"],
  },
  {
    id: "temporal-dragon",
    name: "Dragon Temporel",
    world: "Fantasy",
    cr: 20,
    category: "dragon",
    biomeTags: ["time-rift", "astral"],
    habitatTags: ["temporal-zone"],
  },

  // 🗿 CR 17–20 — TITANS & GÉANTS DIVINS
  {
    id: "fire-titan",
    name: "Titan du Feu",
    world: "Fantasy",
    cr: 19,
    category: "titan",
    biomeTags: ["volcano", "lava-field"],
    habitatTags: ["elemental"],
  },
  {
    id: "storm-titan",
    name: "Titan de l’Orage",
    world: "Fantasy",
    cr: 20,
    category: "titan",
    biomeTags: ["storm", "mountain"],
    habitatTags: ["sky"],
  },
  {
    id: "earth-titan",
    name: "Titan Terrestre",
    world: "Fantasy",
    cr: 18,
    category: "titan",
    biomeTags: ["mountain", "underground"],
    habitatTags: ["elemental"],
  },
  {
    id: "ice-titan",
    name: "Titan des Glaces",
    world: "Fantasy",
    cr: 19,
    category: "titan",
    biomeTags: ["tundra", "glacier"],
    habitatTags: ["elemental"],
  },
  {
    id: "royal-giant",
    name: "Géant du Tonnerre Royal",
    world: "Fantasy",
    cr: 17,
    category: "giant",
    biomeTags: ["mountain"],
    habitatTags: ["wilderness"],
  },
  {
    id: "colossal-stone-giant",
    name: "Géant de Pierre Colossal",
    world: "Fantasy",
    cr: 18,
    category: "giant",
    biomeTags: ["mountain", "cave"],
    habitatTags: ["underground"],
  },
  {
    id: "exalted-fire-giant",
    name: "Géant du Feu Exalté",
    world: "Fantasy",
    cr: 17,
    category: "giant",
    biomeTags: ["volcano"],
    habitatTags: ["wilderness"],
  },
  {
    id: "celestial-giant",
    name: "Géant Céleste",
    world: "Fantasy",
    cr: 19,
    category: "giant",
    biomeTags: ["sky", "sun"],
    habitatTags: ["sky"],
  },
  {
    id: "sylvan-titan",
    name: "Titan Sylvestre",
    world: "Fantasy",
    cr: 17,
    category: "titan",
    biomeTags: ["forest"],
    habitatTags: ["wilderness"],
  },
  {
    id: "abyssal-titan",
    name: "Titan Abyssal",
    world: "Fantasy",
    cr: 20,
    category: "titan",
    biomeTags: ["abyss", "void"],
    habitatTags: ["abyss"],
  },

  // 🔥 CR 17–20 — ÉLÉMENTAIRES ULTIMES
  {
    id: "cataclysm-fire-elemental",
    name: "Élémentaire de Feu Cataclysmique",
    world: "Fantasy",
    cr: 19,
    category: "elemental",
    biomeTags: ["volcano"],
    habitatTags: ["elemental"],
  },
  {
    id: "mountain-earth-elemental",
    name: "Élémentaire de Terre Montagne Vivante",
    world: "Fantasy",
    cr: 20,
    category: "elemental",
    biomeTags: ["mountain"],
    habitatTags: ["elemental"],
  },
  {
    id: "divine-air-elemental",
    name: "Élémentaire d’Air Ouragan",
    world: "Fantasy",
    cr: 18,
    category: "elemental",
    biomeTags: ["storm", "sky"],
    habitatTags: ["elemental"],
  },
  {
    id: "abyssal-water-elemental",
    name: "Élémentaire d’Eau Abyssale Ultime",
    world: "Fantasy",
    cr: 19,
    category: "elemental",
    biomeTags: ["ocean-deep"],
    habitatTags: ["elemental"],
  },
  {
    id: "cosmic-lightning-elemental",
    name: "Élémentaire de Foudre Cosmique",
    world: "Fantasy",
    cr: 20,
    category: "elemental",
    biomeTags: ["cosmic-storm"],
    habitatTags: ["elemental"],
  },
  {
    id: "polar-ice-elemental",
    name: "Élémentaire de Glace Tempête Polaire",
    world: "Fantasy",
    cr: 18,
    category: "elemental",
    biomeTags: ["tundra"],
    habitatTags: ["elemental"],
  },

  // 👹 CR 17–20 — DÉMONS / ABERRATIONS / CONSTRUCTS
  {
    id: "archdaemon-corruption",
    name: "Archdémon du Corruptor",
    world: "Fantasy",
    cr: 20,
    category: "demon",
    biomeTags: ["hell", "abyss"],
    habitatTags: ["demon-lord"],
  },
  {
    id: "archdevourer-abyss",
    name: "Archidévoreur",
    world: "Fantasy",
    cr: 18,
    category: "aberration",
    biomeTags: ["void"],
    habitatTags: ["arcane"],
  },
  {
    id: "void-saviour",
    name: "Sauveur du Vide",
    world: "Fantasy",
    cr: 20,
    category: "aberration",
    biomeTags: ["void"],
    habitatTags: ["void"],
  },
  {
    id: "primordial-horror",
    name: "Horreur Immémoriale",
    world: "Fantasy",
    cr: 19,
    category: "aberration",
    biomeTags: ["abyss", "primordial"],
    habitatTags: ["abyss"],
  },
  {
    id: "transcendant-tentacle",
    name: "Tentaculeur Transcendant",
    world: "Fantasy",
    cr: 18,
    category: "aberration",
    biomeTags: ["void", "arcane"],
    habitatTags: ["void"],
  },
  {
    id: "existence-sculptor",
    name: "Sculpteur d’Existence",
    world: "Fantasy",
    cr: 20,
    category: "construct",
    biomeTags: ["arcane"],
    habitatTags: ["arcane"],
  },
  {
    id: "divine-golem",
    name: "Golem Divin",
    world: "Fantasy",
    cr: 19,
    category: "construct",
    biomeTags: ["temple"],
    habitatTags: ["arcane"],
  },
  {
    id: "arch-spirit-devourer",
    name: "Dévoreur d’Esprit Arch-Démonique",
    world: "Fantasy",
    cr: 20,
    category: "aberration",
    biomeTags: ["void"],
    habitatTags: ["void"],
  },
  {
    id: "ancestral-chimera",
    name: "Chimère Veldique Ancestrale",
    world: "Fantasy",
    cr: 19,
    category: "aberration",
    biomeTags: ["void", "feywild"],
    habitatTags: ["arcane"],
  },
  {
    id: "ultimate-titan-construct",
    name: "Titan Construct Ultime",
    world: "Fantasy",
    cr: 20,
    category: "construct",
    biomeTags: ["mechanical", "arcane"],
    habitatTags: ["arcane"],
  },

  // 💀 CR 17–20 — MORTS-VIVANTS MYTHIQUES
  {
    id: "archlich",
    name: "Liche Archislade",
    world: "Fantasy",
    cr: 20,
    category: "undead",
    biomeTags: ["ruins", "crypt"],
    habitatTags: ["undead"],
  },
  {
    id: "void-lich",
    name: "Liche du Vide",
    world: "Fantasy",
    cr: 20,
    category: "undead",
    biomeTags: ["void"],
    habitatTags: ["undead"],
  },
  {
    id: "ancient-roi-malveillant",
    name: "Roi-Malveillant Ancien",
    world: "Fantasy",
    cr: 16,
    category: "undead",
    biomeTags: ["graveyard", "ruins"],
    habitatTags: ["undead"],
  },
  {
    id: "lord-of-shadows",
    name: "Seigneur des Ombres",
    world: "Fantasy",
    cr: 19,
    category: "undead",
    biomeTags: ["shadowlands"],
    habitatTags: ["undead"],
  },
  {
    id: "apocalypse-knight",
    name: "Chevalier Noir Apocalypse",
    world: "Fantasy",
    cr: 17,
    category: "undead",
    biomeTags: ["void", "ruins"],
    habitatTags: ["undead"],
  },
  {
    id: "primordial-apparition",
    name: "Apparition Primordiale",
    world: "Fantasy",
    cr: 18,
    category: "undead",
    biomeTags: ["void"],
    habitatTags: ["undead"],
  },
  {
    id: "apocalypse-zombie-colossus",
    name: "Colosse Zombie Apocalyptique",
    world: "Fantasy",
    cr: 19,
    category: "undead",
    biomeTags: ["ruins", "wasteland"],
    habitatTags: ["undead"],
  },
  {
    id: "sovereign-spectral-horror",
    name: "Spectre Hurlant Souverain",
    world: "Fantasy",
    cr: 18,
    category: "undead",
    biomeTags: ["shadowlands"],
    habitatTags: ["undead"],
  },

  // ✨ CR 17–20 — FÉE COSMIQUE
  {
    id: "astral-fey-queen",
    name: "Reine des Fées Astrales",
    world: "Fantasy",
    cr: 19,
    category: "fey",
    biomeTags: ["astral", "feywild"],
    habitatTags: ["feywild"],
  },
  {
    id: "cosmic-archfey",
    name: "Arch-Fée Cosmique",
    world: "Fantasy",
    cr: 18,
    category: "fey",
    biomeTags: ["astral"],
    habitatTags: ["feywild"],
  },
  {
    id: "superior-astral-archer",
    name: "Archer Éthérique Supérieur",
    world: "Fantasy",
    cr: 17,
    category: "fey",
    biomeTags: ["astral"],
    habitatTags: ["feywild"],
  },
  {
    id: "eternal-fog-dancer-king",
    name: "Danseur du Brume Céleste",
    world: "Fantasy",
    cr: 18,
    category: "fey",
    biomeTags: ["astral"],
    habitatTags: ["feywild"],
  },
  {
    id: "primordial-season-keeper",
    name: "Gardien des Saisons Éternel",
    world: "Fantasy",
    cr: 20,
    category: "fey",
    biomeTags: ["forest", "winter", "autumn"],
    habitatTags: ["feywild"],
  },
  {
    id: "celestial-hart",
    name: "Cerf Stellaire",
    world: "Fantasy",
    cr: 19,
    category: "fey",
    biomeTags: ["astral"],
    habitatTags: ["feywild"],
  },
];

export default MONSTERS;
